apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: facebooc
  name: facebooc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facebooc
  strategy: {}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "bridge-net"
          }]
      labels:
        app: facebooc
    spec:
      containers:
      - image: schoolofdevops/facebooc:latest
        name: facebooc
        ports:
        - containerPort: 16000
        resources: {}
status: {}
